### ISSUE TITLE
Item and Administrative Statistics Work

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#108]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vantuyls](https://github.com/vantuyls)**
_Thursday Oct 01, 2015 at 21:30 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1323_

----

Oregon State University Libraries is planning a development sprint in the next few weeks to work on building out item level statistics and possibly some administrative statistics reporting. We're interested in hearing from the community about what work you might like to see in these areas. We are tentatively planning to work on the following things:

_Item Level Statistics_
- [ ] Add a table of monthly pageviews and downloads representing the previous 1 year of data
- [ ] Add the ability to download a .csv file of pageview and download data for the item
- [ ] Geospatial representation of pageview an download activity for the item
- [ ] General modifications of the layout of the analytics page to incorporate the above

_Administrative Statistics_
- [ ] Truthfully, we don't have anything at this time, but we're planning to dabble in this area soon...but we also haven't a chance to look at the current admin stats dashboard. 

Any feedback is welcome. We look forward to the conversation.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hectorcorrea"><img src="https://avatars.githubusercontent.com/u/568286?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hectorcorrea](https://github.com/hectorcorrea)**
_Friday Oct 02, 2015 at 13:41 GMT_

----

Tagging @cam156 since she's been doing some admin stats upgrades in ScholarSphere.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Monday Oct 05, 2015 at 22:49 GMT_

----

@cam156 - any thoughts on this? Would love to not plan this work without input from the community!

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Thursday Oct 08, 2015 at 22:37 GMT_

----

So, we've just had our planning meeting and here are the things we are going to have a go at over the next few weeks. We'll only be working on the Item Level Statistics/Analytics page, but on that page we plan to:
- Add a table of monthly pageviews and downloads representing the previous 1 year of data (a moving window of the last 12 months)
- Add the ability to download a .csv file of pageview and download data for the item. The file will include month, year, pageview, downloads for the item from the month of upload to the last complete month. File will also include a header indicating date of creation.
- Make modifications to the time series graph that is currently in place on this page to make it a bit more informative (still unclear exactly what we're going to do here)
- General modifications of the layout of the analytics page to incorporate the above

Again, we'd love to hear from anyone who has comments.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Oct 08, 2015 at 22:42 GMT_

----

:+1: to that plan! If you're planning to do any wireframing or mocking-up prior to dev, feel free to drop those in here for folks to comment on. If not, no worries.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Friday Oct 09, 2015 at 19:48 GMT_

----

Welp, this was my first go at a mock up from about a month ago. I suspect we'll refine this next week, but have a gander.

![](https://cloud.githubusercontent.com/assets/9534576/9237655/2924537c-4101-11e5-9668-610f056f9b92.jpg)

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 09, 2015 at 22:00 GMT_

----

Barring objections or tweaks from @cam156 @mtribone @jcoyne, who've been pinged multiple times in this thread, I'd say run with it!

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Friday Oct 09, 2015 at 22:07 GMT_

----

Even the video game panel in lower left?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 09, 2015 at 22:22 GMT_

----

Gamify it.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cam156](https://github.com/cam156)**
_Monday Oct 12, 2015 at 17:04 GMT_

----

@vantuyls I'm passing this ticket along to our Librarians.  They just said they had a wish for sending users emails about their file level statistics in similar formats to the ones you described above.  Something akin to bpress( sp?), which I have yet to see.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cam156](https://github.com/cam156)**
_Monday Oct 12, 2015 at 17:05 GMT_

----

BTW :+1:  to any work you put in on the file level statistics!

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Monday Oct 12, 2015 at 17:27 GMT_

----

Thanks for the input @cam156 - i wonder about whether that should be incorporated in the file level stats or in some other reporting mechanism. We're also thinking forward to a time when users have profiles (e.g. with lists of digital objects in the repository, user-level statistics, etc.) and I wonder if that would be an appropriate place for users to subscribe to email notifications about their content.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Dec 15, 2015 at 18:08 GMT_

----

@vantuyls I have a question about timelines. Are you interested in doing this work now atop Sufia 6.x, or would you be open to waiting a little and doing this development in Sufia 7 (which saves us from having to migrate/forward-port this work)?

I'll assume 6.x for now, but will be happy to change the milestone to 7.x. :smiley:

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Wednesday Dec 16, 2015 at 20:25 GMT_

----

@mjgiarlo so, we have this up and running in our local system now, but it needs a tad more work before i think it is shareable (right @straleyb?). We'll wait until 7.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Wednesday Dec 16, 2015 at 21:00 GMT_

----

OK, great! I've moved it to the backlog. Thanks, @vantuyls & @straleyb

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Wednesday Dec 21, 2016 at 00:02 GMT_

----

Ping @hannahfrost :arrow_up:
