### ISSUE TITLE
Updates to Add/Edit Work UI

### ISSUE THREAD

**Issue by ggeisler** [samvera/hyrax#1218]
Ticket #695 contains a range of suggestions for improving the UI of the Add New Work page. Because some of the suggestions in that ticket are part of unresolved discussions (around admin sets), that ticket is not immediately actionable, so this ticket extracts the improvements we should be able to make in the short-term to improve the Add New Work page.

@hannahfrost Please review and make sure I haven't forgotten anything from our discussion about this.

# Progress

This issue was decomposed into the following issues:

- [x] #2026 
- [x] #2025 
- [x] #2028 
- [x] #2030 
- [x] #2034 
- [x] #2245 
- [x] #2247 
- [x] #2248 
- [x] #2249 

# Remove icons in tabs
There are a lot of icons in the application and I'm not sure using them here provides enough value to justify the additional visual clutter and inconsistency with other tabs that don't use an icon. 

# Descriptions tab
Remove the text before the Title heading, so the top of the tabbed page looks like this:

<img width="752" alt="descriptions-tab" src="https://cloud.githubusercontent.com/assets/101482/24631618/d91c1f92-1875-11e7-8893-3040befc79e6.png">

# Files tab
Updates to deal with 1) works are not always required to have files, and 2) an implementor might not have browse_everything enabled:

## If browse_everything is enabled:

![files-a](https://cloud.githubusercontent.com/assets/101482/25107598/403ce66a-2385-11e7-943b-c28c02c17521.png)

## If browse_everything is **not** enabled:
* Don't display the introductory text except the first sentence
* Don't display the browse_everything button

![files-no-browse-everything](https://cloud.githubusercontent.com/assets/101482/25107620/5fd57e88-2385-11e7-8756-3d3690f4e291.png)

# Relationships tab

- Rename the label for the administrative set select menu to just "Administrative Set"
- Rename the heading for the collections section to just "Collections"
- Update the Collection section to enable adding work to a collection via either a select menu (Example 1 below) or via a search/autocomplete input (similar to what is used for adding users to Admin Set participants - Example 2). Example 1 is preferable if we think repositories are unlikely to have more than 15 or so collections. If it is reasonable to expect repositories to have more than 15 collections, we should probably go with the search/autocomplete input shown in Example 2.
- Add a table showing what collections the work is currently part of (so the user doesn't try to add the work to a collection it is already part of). If this is a new work or an existing work that hasn't been added to any collections, omit the "This work is currently in these collections" heading and the table beneath it.

## Example 1 - add collection via select menu
![new_generic_work____hyrax 2](https://user-images.githubusercontent.com/101482/27147708-9cd4ebbc-50f2-11e7-80ea-d31ac666e886.png)

## Example 2 - add collection via search input
![new_generic_work____hyrax](https://user-images.githubusercontent.com/101482/27147733-b2594b04-50f2-11e7-962d-71d267b408cb.png)

## Updated version of Example 1
Based on work done by the Collections Extensions WG since this ticket was first created, here's an updated version of Example 1:

![work-new-edit-relationships](https://user-images.githubusercontent.com/101482/28549104-de82708e-708c-11e7-858a-2e46f47e05a3.png)

# Sharing tab
Rename tab. (ignore the different order of the first two tabs in the mockup.) More significantly, rearrange the form elements to more closely match the pattern used on the Add/Edit Admin Sets Participants tab and other places, since they are very similar features. (Not shown in the mockup below: each entry in the "Currently Shared With" table should have a "Remove" button.)

![sharing-tab](https://cloud.githubusercontent.com/assets/101482/24631767/6986d478-1876-11e7-92f1-b6b0ac2b4edd.png)

**Comment by hannahfrost** [comment]
@ggeisler You captured everything we had discussed yesterday. Thanks for creating the ticket. 

For the add-to-collection interaction, I think Example 1 is preferable. While we should expect that there will be many collections, a given depositor will likely only be able to deposit to a subset of them. If the dropdown list only shows those collections for which the user has deposit access, the list is likely to remain manageable. Is that how you were suggesting it will work?

Example 2 is less preferable because the depositor may not know the names of collections to which they can deposit, making it hard for them to search.

**Comment by hannahfrost** [comment]
@mjgiarlo I'd like to move this to the Ready column (pending resolution of the discussion above with @ggeisler). Wonder if we need to break out the Relationships tab work to its own ticket.

**Comment by ggeisler** [comment]
@hannahfrost Yep, your assumption of how Example 1 would work for selecting collections is what I was thinking. And I agree that the select menu is the preferable approach and the list is likely to be manageable given it will be limited by user access privileges.

**Comment by ggeisler** [comment]
I noticed that we appear to be using the Select2 plugin elsewhere in the app (e.g., Admin Set edit, Thumbnail field) so another alternative for the "Add to collection" widget in the Relationships tab could be that plugin, one version of which appears to provide a combination of searching and a select list.

**Comment by mjgiarlo** [comment]
@hannahfrost I'm thinking this should be decomposed into:

- [ ] Remove icons from tabs
- [ ] Descriptions tab changes
- [ ] Files tab changes
- [ ] Relationships tab changes (go with example 1, it sounds like?)
- [ ] Sharing tab changes

Each of which could be added to the Ready column beneath the bugs. How does that sound?

**Comment by hannahfrost** [comment]
@mjgiarlo I'm starting to decompose this ticket. 

Files tab changes is now covered by https://github.com/samvera/hyrax/issues/2025

**Comment by mjgiarlo** [comment]
Decomposed into:
* https://github.com/samvera/hyrax/issues/2026
* https://github.com/samvera/hyrax/issues/2025
* https://github.com/samvera/hyrax/issues/2028
* https://github.com/samvera/hyrax/issues/2030
* https://github.com/samvera/hyrax/issues/2034

**Comment by mjgiarlo** [comment]
Thanks, @hannahfrost!
