### ISSUE TITLE
Collections: Adjust routes to accommodate a public landing page and permission templates

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1380]
### Descriptive summary

Adjust existing routes and define new routes to separate management of collections from public Define the routes for permission templates usage in collections.  I'm not sure what is needed.

### Rationale

See model issue for rationale.

### Implementation

The primary management routes for collections are currently defined at...
- new/edit/show - https://github.com/samvera/hyrax/blob/master/config/routes.rb#L49-L59
- dashboard (All) - https://github.com/samvera/hyrax/blob/master/config/routes.rb#L124
- dashboard (Yours) - https://github.com/samvera/hyrax/blob/master/config/routes.rb#L136-L138

There may be other related definitions.

Changes needed...
- [x] Need show route that is accessible from admin menu only (e.g. /dashboard/collections/:id) (#1427)
- [x] Need show route for (landing page) that is accessible by public users (e.g. /collections/:id) (#1428)
- [x] Need to move CrUD routes for collections to /dashboard/collections
  - [x] Move new/edit and partials to app/views/dashboard/collections (#1374 & partials in related work below)
- [ ] Need routes related to permission templates - Moved to issue #1523

More exploration is needed on how to integrate with permission templates and their impact on routes.

![question_24](https://cloud.githubusercontent.com/assets/6855473/13064236/f2f04cbe-d41e-11e5-9674-e9a56a6326e6.png) **QUESTION:** Should all management routes be moved under the admin path, leaving only the landing page directly off home path (e.g. /admin/collections/...)?  What would be the impact of this change?

_Answer:_ Move to /dashboard/collections.  See comments for more details.

### Related work

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | (this issue) |
| Controller               | # |
| Model                    | #1383 |
| View - Index            | #1417 |
| View - Show - Admin      | #1427 |
| View - Show - Landing    | #1428 |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | #1377 |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by mjgiarlo** [comment]
> QUESTION: Should all management routes be moved under the admin path, leaving only the landing page directly off home path (e.g. /admin/collections/...)? What would be the impact of this change?

What routes do you include in "all management routes" here?

**Comment by elrayle** [comment]
@mjgiarlo 
Right now the CRUD routes are not under /admin.  The proposal is to move CRUD to...
* /admin/collections/index
* /admin/collections/create
* /admin/collections/new
* /admin/collections/edit
* /admin/collections/update
* /admin/collections/show

The public landing page will not be under the admin menu
* /collections/show

If collection management is going to happen from the admin menu, it makes sense to me that they would be under /admin.  But I didn't know if there would be unintended consequences of making that change.  The alternative is to leave all the CRUD under /collections with /collections/show being the public landing page AND create /admin/collections/show as the admin show page.

**Comment by mjgiarlo** [comment]
What if we consolidate under /dashboard/ instead of /admin/, since the consolidated dashboard gives us extra flexibility in terms of who sees what there? It's no longer the case that there's an "admin" section of the UI (though it is true that Hyrax's defaults mean that some sections of the dash are only visible to admins).

**Comment by elrayle** [comment]
@mjgiarlo Just to be clear, the suggestion is that CRUD will be under /dashboard, with the proposed CRUD becoming...

* /dashboard/collections/index
* /dashboard/collections/create
* /dashboard/collections/new
* /dashboard/collections/edit
* /dashboard/collections/update
* /dashboard/collections/show

The public landing page will be...

*  /collections/show

**Comment by mjgiarlo** [comment]
@elrayle :shipit:

**Comment by laritakr** [comment]
@mjgiarlo @elrayle Does this discussion negate the work I've done on issue #1427 ?

**Comment by elrayle** [comment]
@laritakr It doesn't negate the work.  I does mean that the location of the view code would move to /app/views/hyrax/dashboard/show.html.erb.

**Comment by elrayle** [comment]
Understanding collections views and controllers...

| view | controller#action | comments |
| ----- | ------------------- | ------------ |
| views/hyrax/dashboard/collections/index | controllers/hyrax/dashboard/collection_controller#index | admin All Collections tab in dashboard |
| views/hyrax/dashboard/collections/show | controllers/hyrax/dashboard/collection_controller#show | manager's view of the collection |
| views/hyrax/dashboard/collections/new | controllers/hyrax/dashboard/collection_controller#new | |
| views/hyrax/dashboard/collections/edit | controllers/hyrax/dashboard/collection_controller#edit | |
| views/hyrax/my/collections/index | controllers/hyrax/dashboard/collection_controller#index | all users Your Collections tab in dashboard |
| views/hyrax/collections/show | controllers/hyrax/collection_controller#show | public landing page |

**Comment by elrayle** [comment]
PR #1499 merged into master.  Rebase of master into collections-sprint to follow soon.  Then any remaining changes PR #1490, if any, will be created in a new branch and a separate PR submitted.

**Comment by elrayle** [comment]
All functionality for this issue is complete except...
* permission template routes related to participants for collections.  Moved to issue #1523.
