### ISSUE TITLE
Collections: Update UI for index views (All/Your) of MVC for Managing Collections

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1417]
### Descriptive summary

Add code to implement modifications of the index view for listing collections.

### Rationale

See model issue for rationale.

### Implementation

**Edit Files:**
* index for All/Your Collections - [app/views/hyrax/my/collections/index.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections/index.html.erb)
* all other files are under
  * [app/views/hyrax/my/collections](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections) - specific to collections
  * [app/views/hyrax/my](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my) - shared with works

#### Expected user interactions

Update the UI view for listing collections.

From this page, a user can...
- [x] see a list of existing collections and admin sets #1509
- [x] ability to filter list by collection type and visibility #1511
- [x] bulk actions on collections #1510
- [x] click a button to create a new collection shows a modal #1506
- [x] process edit action for an existing collection #1508
- [x] process delete action for an existing collection #1507
- [x] process add collection in another collection action for an existing collection #1512

This issue will close when all sub-issues are complete.

### Mockup

An administrative user sees two tabs:

![collection-index-admin-user](https://user-images.githubusercontent.com/101482/28932471-6aae94c2-782e-11e7-8a87-d74179c0a2be.png)

A non-admin user just sees the Your Collections tab:

![collection-index-end-user](https://user-images.githubusercontent.com/101482/28932481-7932e160-782e-11e7-9baa-457e5c59fd97.png)

#### Issues related to UI work for nesting

* #1417 original UI epic for admin index
* #1509 admin index - listing of collections - includes description of action menu items
* #1512 process `Add collection to another collection` action + modal for selecting other collection  (This one has the brain dump list of things needed for nesting)
* #1377 relationship partial for edit form

#### Collections original epic issues (mainly organized by UI)

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | #1380 |
| Controller               | # |
| Model                    | #1383 |
| View - Index             | (this issue) |
| Index: Collection List   | #1509 |
| Index: Filter List      | #1511 |
| Index: New Modal         | #1506 |
| Index: Edit Action       | #1508 |
| Index: Delete Action     | #1507 |
| Index: Add as Subcollection Action | #1512 |
| Index: Bulk Actions      | #1510 |
| View - Show - Admin      | #1427 |
| View - Show - Landing    | #1428 |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | #1377 |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by jcoyne** [comment]
If I recall correctly AdminSets are not visible to end users of the discovery interface. Do you intend to change that?

**Comment by jcoyne** [comment]
This issue seems too big to be actionable. Might I suggest you tag this as an "Epic" and break the work up into sub-issues?

**Comment by ggeisler** [comment]
@elrayle As @jcoyne says above, the current behavior is that admin sets are just for administrative management of items and collections are used for enabling non-admin users to view groupings of items. Is there a real use case for needing to show admin sets to non-admin users? 

Given the future goal is to make admin sets just another type of collection, it doesn't seem worth doing the extra work in the meantime to expose admin sets to non-admin users unless we know of a valid use case where that couldn't be achieved through collections.

**Comment by adamjarling** [comment]
@elrayle Here's a list of items which still need completion from the checkbox task list above.  All current work is in the branch: `collections-#1417-index_views_managing_collections`

- Table columns
  - **Type** - Verify this is being referenced correctly.
  - **Visibility** - I took this from Works, but perhaps we just want text output instead of the label tag/link?
  - **Items** - Count calculation.
  - **Last modified** - Currently just pulling in created date from the Solr document object.
- bulk actions on collections
  - add checkbox for select/deselect all
  - add Bulk actions drop list (e.g. Delete selected collections)
- click a button to create a new collection (see note below on AdminSets)
  - Apply permissions logic to layout elements.
- click edit for an existing collection (see note below on AdminSets)
  - Apply display logic.
- click delete for an existing collection
  - Handle the confirm delete modal action.  I created an event listener in `app/assets/javascripts/hyrax/collections.js` for this.
- Various text translations in `hyrax.en.yml` file.
- Spec testings re-activate and update in `spec/features/collection_spec.rb` and `spec/views/hyrax/my/collections/_list_collections.html.erb_spec.rb`.

**Comment by elrayle** [comment]
@jcoyne @ggeisler I was under the impression that a site could choose whether admin sets were or were not discoverable.  I am very happy to hear that they are always not discoverable.  That will NOT be changed by the collection extensions work.

**Comment by adamjarling** [comment]
@elrayle Should this branch be left open?

**Comment by adamjarling** [comment]
@elrayle I believe this can be closed?  Looks like everything was accounted for in other issues, and the UI looks like it reflects what this issue addresses.

**Comment by elrayle** [comment]
@adamjarling Thanks for reviewing the status of this issue.
