### ISSUE TITLE
Create a consistent UX for new/edit forms

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1527]
### Descriptive summary

Determine a consistent user experience for new/edit forms for collection types, admin sets, collections, and works.  The labeling of the save/cancel buttons vary and the behehaviors for those buttons follows one of two patterms.

### Rationale

A consistent user experience leads to less confusion and increased satisfaction.

### Expected behavior

TBD - @ggeisler What are you intending as the expected behavior for these?  
- specified in #1577 and #1578. I also updated the [analysis of current behavior](https://wiki.duraspace.org/x/cq82BQ) table in the wiki with my recommendations/responses

The following are laid out in an easy to read table in an [analysis of current behavior](https://wiki.duraspace.org/x/cq82BQ) wiki page.  They are mentioned here too for documentation in the issue.

Major question areas:
- [x] labels for buttons - see #1577 
  * New:  Save vs. Create _Entity_
  * Edit:  Save vs. Update _Entity_
- [x] forwarding action for save buttons - see #1578 
  * Edit: Should save stay on the edit form or return to show page or index page (collection types only because they don't have show pages)
- [x] forwarding action for cancel buttons - see #1578 
  * New: Should it always go back to index?  Some don't.
  * Edit: Should it go back to index page or show page (if one exists)?  Right now, two go to index page, one goes to Home, and one goes to Dashboard.  The last two seem wrong.

### Actual behavior

See the [analysis of current behavior](https://wiki.duraspace.org/x/cq82BQ) in the wiki.

### Steps to reproduce the behavior

To get to each of the NEW forms...
1. Dashboard -> Settings -> Collection Types -> Create new collection type
1. Dashboard -> Repository Contents -> Administrative Sets -> Create new administrative set
1. Dashboard -> Repository Contents -> Collections -> New Collection
1. Dashboard -> Repository Contents -> Works -> Add new work

Note: The process for creating admin sets and collections is shifting.  You might also try...
1. Dashboard -> Repository Contents -> Collections -> Create new collection -> select Admin Sets from collection type modal 
1. Dashboard -> Repository Contents -> Collections -> Create new collection -> select User Collection from collection type modal 

To get to each of the EDIT forms...
1. Dashboard -> Settings -> Collection Types -> click Edit for any of the existing collection types
1. Dashboard -> Repository Contents -> Administrative Sets -> click the title of an existing admin set -> click Edit button
1. Dashboard -> Repository Contents -> Collections -> click the title of an existing collection -> click Edit button
1. Dashboard -> Repository Contents -> Works -> Add new work

Again depending on the development process, this may have changed for admin sets and collections to be...
1. Dashboard -> Repository Contents -> Collections -> click the title of an existing admin set -> click Edit button
1. Dashboard -> Repository Contents -> Collections -> click the title of an existing collection -> click Edit button

### Related work

Issue #1374 - New/Edit form changes for collections
Issue #1348 - PR #1476 - Add New/Edit form for collection types

**Comment by elrayle** [comment]
#1578 fixed by PR #1647 Fix redirects for collection/work edit save and cancel

**Comment by elrayle** [comment]
Issue #1577 & #1578 address these UI changes.
