### ISSUE TITLE
Implement operations functionality and UI

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#159]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Aug 26, 2016 at 20:46 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2571_

----

# Description

During our first Hydra-in-a-Box work cycle, we added the concept of operations to Hyrax, and made use of operations to surface more information about the batch create workflow.

An operation is a lightweight wrapper around potentially long-running processes. An operation can be in one of four states:
1. **pending**: the operation has not yet begun
2. **performing**: the operation is being performed
3. **success**: the operation is done and it did what the user expected
4. **failure**: the operation is done and it didn't do what the user expected

An operation can have children operations.

# Subtasks

- [ ] [Background jobs should be wrapped by operations](https://github.com/projecthydra-labs/hyrax/issues/160)
- [ ] [Add logs/status for batch and item level operations](https://github.com/projecthydra-labs/hyrax/issues/118)
- [ ] [Dashboard should allow users the ability to list and show operations they created](https://github.com/projecthydra-labs/hyrax/issues/161)
- [ ] [Admin Dashboard should allow the ability to list and show all operations](https://github.com/projecthydra-labs/hyrax/issues/162)

**Comment by no-reply** [comment]
We probably need to clarify and document the design goals for operations.

cc: @mjgiarlo @jcoyne

**Comment by mjgiarlo** [comment]
Back in the pre-ActiveJob Sufia days, we were content to tell people "Just use the Resque UI for this."

I believe we initially undertook this work to expose background job status information to e.g. tenant administrators in Hyku. But I suspect that this information is useful more broadly to Hyrax admins (and possibly even end-users who want to know more about long-running work related to their content).

**Comment by RudyOnRails** [comment]
> But I suspect that this information is useful more broadly to Hyrax admins (and possibly even end-users who want to know more about long-running work related to their content).

@mjgiarlo you suspect correctly - we have a ticket here at AIC to one day give users a better understand of those behind the scenes processes, and answer those "where's my stuff at" emails...

**Comment by vantuyls** [comment]
Agreed, thanks @no-reply

**Comment by vantuyls** [comment]
@no-reply i can close this one, but can you find and close the related issues?
