### ISSUE TITLE
On Add/Edit Work page, various updates to Relationships tab

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#2034]
### Descriptive summary

A set of changes to the Relationships tab, including renaming labels and headers, adding confirmation modals, and filling out some of the functionality.

### Rationale

These changes collectively make the information and interactions on this tab more clear, concise and consistent with other similar features in Hyrax.

### Expected behavior

- [ ] Rename the label for the administrative set select menu from “Add as member of administrative set” to simply "Administrative Set" (#2242)
- [ ] Rename the heading for the collections section to just "Collections" (not pictured in the mockup below) (#2243)
- [ ] Update the Collection section to enable adding work to a collection via a select menu and button. Text label to the left of the select menu is “Add to collection”. Button is to the right of the select menu and has label  “Add”. (#2245)
- [ ] Add a table below the Collection section showing what collections the work is currently part of (so the user doesn't try to add the work to a collection it is already part of). If this is a new work or an existing work that hasn't been added to any collections, omit the "This work is currently in these collections" heading and the table beneath it. (#2245)
- [ ] The feature to add a child work is restructured to be consistent with the interaction for adding the work to a collection, under Collections above. (#2247)
- [ ] Label for button to add a new work as a child is changed to read "Deposit new work as a child of this work" (#2248)
- [ ] Add confirmation modals when the user selects to remove a collection which this work is currently in or when they select to remove a child work from the work. Text for the two modals is provided in the mockup below. (#2049)

![relationships-tab-changes](https://user-images.githubusercontent.com/1801076/32185304-032abdd0-bd5c-11e7-9196-3568318ae19d.png)

**Comment by hannahfrost** [comment]
Decomposed from https://github.com/samvera/hyrax/issues/1218

**Comment by jcoyne** [comment]
Closing because this was broken out into subtickets.
