### ISSUE TITLE
Test Spanish language support

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#206]
Switch into `Español` and click around the UI, looking for areas where we need to add translations. Also, please verify that the translations we have make sense; a number of them were based on Google Translate, where we didn't have access to a native Spanish speaker.

Make a log of changes that need to be made in this ticket (or, if you're comfortable submitting pull requests, submit the code changes yourself).

**Comment by mjgiarlo** [comment]
Closes https://github.com/projecthydra-labs/hyku/issues/564 as a replacement.

**Comment by hannahfrost** [comment]
- [ ] Terms of use page - header needs translation
- [ ] User Notifications - header needs translation
- [ ] User Notifications - “Delete All” button
- [ ] Configuration > Labels - form is incompletely translated
- [ ] Configuration > Appearance - Image upload stuff needs translation
- [ ] Configuration > Content Blocks - All labels for the various blocks need translation
- [ ] Configuration > Technical Settings - Everything needs translation
- [ ] Statistics - Everything needs translation
- [ ] Review Submissions - Everything needs translation

**Comment by laritakr** [comment]
Admin/admin_sets show page content that needs translation: 
- Total Items count for admin set
- Column headings for works list (partial: hyrax/collections/_show_document_list)
- Status column data (document.workflow_state)
- Action column dropdown button title and some of the content
- Titles on "document detail" section (partial: hyrax/collections/_show_document_list_row)

**Comment by jcoyne** [comment]
@mjgiarlo is this done now?  Will it ever be done?  What is the completion criteria?

**Comment by hannahfrost** [comment]
Note I consulted with a native spanish speaker and determined that "trabajo" is the appropriate translation of "work" generally in the context of Hyku ("obra" is rarely used for anything other than art or plays).

**Comment by mjgiarlo** [comment]
@jcoyne As I see it, this ticket is an epic that wraps the following work:

- [ ] Improve existing Spanish translations to be idiomatic (many are from Google Translate). That would be a huge amount of work, and I'm not sure we can reasonably expect anyone to come along and pick up that as a ticket. Suggest instead adding some documentation to the README that says "We support Spanish and Chinese too! Are you a native Spanish or Chinese speaker? If so, we welcome suggestions on the Spanish and Chinese words and phrases."
- [ ] Improve existing Chinese translations to be idiomatic. See above.
- [ ] i18nize all the things that are still using hard-coded English strings. @hannahfrost and @laritakr have listed specific places to start above. This would be a new ticket that would be actionable. We should also expand the README text above to say "Do you see English in the application where you would expect to see Spanish (or Chinese)? If so, file an issue."

**Comment by jcoyne** [comment]
@mjgiarlo I don't think "Improve X" should be a valid ticket because we can't write acceptance criteria for them.  They should be "goals" and put in the README or something.

**Comment by mjgiarlo** [comment]
@jcoyne That's why I said we should handle that in the README vs. ticketizing it. Sorry if the wall o' text was unclear.

**Comment by mjgiarlo** [comment]
Now that I've created a targeted issue for this, I'm closing this issue. In particular, see the following:

* https://github.com/samvera/hyrax/issues/1386
* https://github.com/samvera/hyrax/issues/1386#issuecomment-317822078
* https://github.com/samvera/hyrax/pull/1388

Thanks, all!
