### ISSUE TITLE
Collection public show page search bar location implies untrue behavior

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#2163]
### Descriptive summary

On the collections sprint branch, the public collection show page has the search bar between the subcollection list and the works list. It should be located above both lists.

In addition, the header image was supposed to show collection type, but instead was changed to show "Collection". See the dashboard show page for more details.

### Rationale

The search behavior searches both works and subcollections. Unless this behavior is modified, the search bar should be above both. Having it located between the two lists implies that it only searches works. 

Also, collection type was the intended content to be shown on the header image.

Related to https://github.com/samvera/hyrax/pull/2072

### Tasks to complete in this issue:

- [x] Change label in header where it says "Collection" to instead show the collection type in the similar format. 
- [x] Move the search bar above the subcollections list since it searches both lists.

**Comment by laritakr** [comment]
![screen shot 2017-11-13 at 10 37 43 am](https://user-images.githubusercontent.com/17851674/32734364-d2468d20-c85f-11e7-9cd4-e158701b72e4.png)

**Comment by elrayle** [comment]
Fixed by PR #2476

**Comment by elrayle** [comment]
Tasks for this PR: (make it match the behavior and appearance seen on admin collection show page)
- [ ] Move search box above subcollections
- [ ] Reword placeholder text in search box to 'Search subcollections and works in this collection.'

**Comment by elrayle** [comment]
Fixed by PR #2585.

NOTE: PR lists a few follow-on issues to further solidify the consistency of the UI.
