### ISSUE TITLE
Default Admin Set exceptions

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#236]
The default admin set should not be treated like other admin sets. At a minimum:

- [ ] It should not appear in the list of Featured Collections on the homepage
- [ ] It should not be delete-able
- [ ] ... add yours here. Any other exceptions you can think of, @vantuyls @jcoyne @hannahfrost ?

**Comment by hannahfrost** [comment]
- [ ] It should not have a representative thumbnail

**Comment by no-reply** [comment]
@vantuyls @elrayle do either of you have thoughts about this? I'm inclined to avoid the special cases this implies unless we can articulate more clearly what these exceptions are about.

Is the default admin set meant to be a different thing, conceptually, from any other admin set/collection?

**Comment by vantuyls** [comment]
i'm also a little confused about why this is needed. Maybe @mjgiarlo or @hannahfrost can offer some insight?

**Comment by mjgiarlo** [comment]
I'm not sure this is still needed.
