### ISSUE TITLE
Tracking direct downloads (as well as clicked events) in GA

### ISSUE THREAD

**Issue by revgum** [samvera/hyrax#2400]
### Descriptive summary
Hyrax tracks "downloads" by way of the user clicking the download link on the page.. this doesn't capture incoming traffic directly to the downloads controller. In ScholarsArchive, we have disabled the click event on the page and replaced tracking of the event with a behavior on the downloads controller to send a Google Analytics event from the server side.

### Rationale
This covers tracking download events both after the user has clicked the button and if the request came in directly to the server.

### Steps
- [ ] Remove ga_events.js (https://github.com/samvera/hyrax/blob/master/app/assets/javascripts/hyrax/ga_events.js)
- [ ] Add Staccato gem
- [ ] Create behavior: https://github.com/osulp/Scholars-Archive/blob/master/app/controllers/concerns/scholars_archive/download_analytics_behavior.rb
- [ ] Add behavior to downloads controller

**Comment by no-reply** [comment]
i think the steps in this issue might be over-specific, but the need to track hyrax downloads systematically remains.
