### ISSUE TITLE
Admin Dashboard Redesign

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2541]
### Descriptive summary
The Admin Dashboard should show a table of the number of works by collection

- [x] Paginated Collection table starting with 10 (?) collections listed
- [x] Paginated Works table starting with 10 (?) works listed
- [x] Toggle on table to show Most Recently Updated vs. Pinned collections or works
- [x] Add concept of pinning a collection or work to this table
- [x] Wire up Total Visitors, Returning Visitors and New Visitors Boxes
- [ ] Repository Objects donut chart toggles between Visibility, Work Types, and Resource Types
- [x] Dropdown to select number of records on each summary table.

![a5-analytics-dashboard-collections-works](https://user-images.githubusercontent.com/9534576/35238732-4291554e-ff63-11e7-8d4f-4c0ad2190ee0.png)

![a2-analytics-dashboard-collections-pinned](https://user-images.githubusercontent.com/9534576/35357158-8c3ab758-0107-11e8-9702-e1baaf13662d.png)

Refer To:
https://wiki.duraspace.org/pages/viewpage.action?pageId=87467336

**Comment by lfarrell** [comment]
Are admin sets moving to a different view? They're on the current default admin view.

**Comment by lfarrell** [comment]
There doesn't currently seem to be a concept of "pinned" anywhere in hyrax. Would we want to set this on the admin dashboard or on the individual collection's page? Also, how would we want to store this info, solr, db, local browser storage, even? Seems pinned collections could even vary by user even within the same institution.

**Comment by lfarrell** [comment]
As best as I can tell there's also no concept of "last updated" for a collection. Would we want the most recently updated record in the collection? That seems wrong, though.

**Comment by vantuyls** [comment]
I wonder if the "featured" functionality is similar enough to "pinned" to be useful. 

As for "last updated", i think we do want to use the most recently updated object in the collection. Can you say more about why that might not be right?

**Comment by lfarrell** [comment]
I was thinking it would be the last time the collection was changed, e.g. a work was added or removed.

**Comment by vantuyls** [comment]
For the statistics boxes across the top of the page:
I think we're settled on the definitions of "visitor" and "session" over in https://github.com/samvera/hyrax/issues/2850

The clarification of these definitions, and need to report compatible analytics from Google Analytics and Matomo has resulted in us changing the design of this page such that there are only **three** analytics boxes shown:
- Registered Users
- Total Visitors
- Total Sessions
