### ISSUE TITLE
Depositor Analytics Redesign

### ISSUE THREAD

**Issue by nestorw** [samvera/hyrax#2551]
### Descriptive summary

Depositor statistics visible on the Reports > Users page. Works for a single depositor should include  child works and a fileset of my work.

- [ ] Total number of times the page with my work has been viewed (pageviews).
- [ ] Timeseries graphic showing number of times a page with my work has been viewed over time.
- [ ] Number of unique visitors of my work.
- [ ] Total number of downloads of a file in a work.

### Mockups
<img width="1268" alt="e3-analytics-user" src="https://user-images.githubusercontent.com/1766876/35350939-6ed71296-010d-11e8-8151-a1bc99266b5a.png">
<img width="1263" alt="e2-analytics-users-monthly" src="https://user-images.githubusercontent.com/1766876/35350940-6ee4cbc0-010d-11e8-928b-0ed7190d5431.png">
<img width="1317" alt="e1-analytics-users-summary" src="https://user-images.githubusercontent.com/1766876/35350941-6ef3c1ac-010d-11e8-9566-93012d0e5e64.png">
