### ISSUE TITLE
Work Analytics Status Page

### ISSUE THREAD

**Issue by nestorw** [samvera/hyrax#2555]
### Descriptive summary

This represents the page at Reports > Works
**Status Tab**

Backend tasks that need to be completed in order to get data to the front-end

- [ ] #2719 Collect Work Status History
- [ ] #2720 Collect Work Visibility History

For the form:

 - [ ] time period drop down
 - [ ] filters drop downs (work type, status, visibility)
 - [ ] sort column (status)
 - [ ] radio buttons for summary tables and month-by-month totals
 - [ ] build reporting text (text immediately below report title - summary of filters and totals)
 - [ ] table download button with options for csv download
 - [ ] for Month-by-month - table for Visibility status
 - [ ] for Month-by-month - table for Publication status
 - [ ] for Summary table - paginated table of works

### Mockups
<img width="1318" alt="c2-analytics-works-status-monthly" src="https://user-images.githubusercontent.com/1766876/35351693-b17edc26-010f-11e8-8b7b-6d7edc6601f3.png">
<img width="1266" alt="c1-analytics-works-status-summary" src="https://user-images.githubusercontent.com/1766876/35351694-b18b81ba-010f-11e8-850f-aad7adcca296.png">

### Related work

https://wiki.duraspace.org/pages/viewpage.action?pageId=87467336

**Comment by vantuyls** [comment]
Needs:
- [ ] Customize Report form including:
- [ ] time period drop down
- [ ] filters drop downs (work type, status, visibility)
- [ ] sort column (status)
- [ ] radio buttons for summary tables and month-by-month totals
- [ ] build reporting text (text immediately below report title - summary of filters and totals)
- [ ] table download button with options for csv download 
- [ ] for Month-by-month - table for Visibility status
- [ ] for Month-by-month - table for Publication status
- [ ] for Summary table - paginated table of works

**Comment by vantuyls** [comment]
Status, Attributes, and Activity buttons across the top of this view may be replaced by a layer of nesting in the left side menu under Reports-Works

**Comment by sethaj** [comment]
From what I'm gathering from the mockups, "status" seems to be a mix of:

1) Hydra::AccessControls::AccessRight (Embargo for example) 
2) The "status" field that relates to sipity workflows, "suppressed_bsi" in solr where "false" means Published, "true" means Unpublished and "nil" means Unknown
3) The workflow state as defined in sipity, so "In Review" would mean I guess be a sipity_workflow_state.name of "pending_review". I guess. But since sipity can take aribitrary workflows this could maybe be anything.

Is there a definition of "status" somewhere already, or do we need to create that?

**Comment by sethaj** [comment]
Theres also a work in the above mockup that simultaniously has a status of "Unpublished" but also has a Publication Date. Maybe Publication Date is wrong here? 

We have date_uploaded and date_modified in solr/fedora, but I'm not sure if that's helpful. 

We could assume that the entry is in the sipity_entries table and if the entity is "deposited" or Published (so "suppressed_bsi" is false) we can use the sipity_entries.updated_at date for Publication Date? Need to find out if there's a "Publication Date" recorded somewhere that should be used here, or if we need to create one.
