### ISSUE TITLE
Work Analytics Activity Page

### ISSUE THREAD

**Issue by nestorw** [samvera/hyrax#2557]
#### View the number of unique downloads for files in any given collection.
This represents the page at Reports > Works
**Activity Tab**

### Mockups
<img width="1265" alt="c6-analytics-works-activity-monthly" src="https://user-images.githubusercontent.com/1766876/35351769-ed0675a6-010f-11e8-9f3f-9574ee4fd9bb.png">
<img width="1285" alt="c5-analytics-works-activity-summary" src="https://user-images.githubusercontent.com/1766876/35351770-ed130f50-010f-11e8-9254-80ef39d905ee.png">

### Related work

https://wiki.duraspace.org/pages/viewpage.action?pageId=87467336

**Comment by nestorw** [comment]
Status, Attributes, and Activity buttons across the top of this view may be replaced by a layer of nesting in the left side menu under Reports-Works

See: #2565

**Comment by nestorw** [comment]
Needs:
- [ ] Customize Report form including:
- [ ] time period drop down
- [ ] filters drop downs (work type, status, visibility)
- [ ] sort column (status)
- [ ] radio buttons for summary tables and month-by-month totals
- [ ] build reporting text (text immediately below report title - summary of filters and totals)
- [ ] table download button with options for csv download 
- [ ] for Month-by-month - table for Summary of user activity
- [ ] for Month-by-month - table for monthly user activity
- [ ] for Summary table - paginated table of works by user activity
