### ISSUE TITLE
Work Analytics Attributes Page

### ISSUE THREAD

**Issue by nestorw** [samvera/hyrax#2558]
### Descriptive summary

This represents the page at Reports > Works
**Attributes Tab**

### Mockups
<img width="1247" alt="c3-analytics-works-sttributes-summary" src="https://user-images.githubusercontent.com/1766876/35351819-1f81760c-0110-11e8-8f29-8d1c6c2b76da.png">
<img width="1260" alt="c4-analytics-works-attributes-monthly" src="https://user-images.githubusercontent.com/1766876/35351820-1f8a8f08-0110-11e8-937e-00716f36da9b.png">

### Related work

Link to related tickets or prior related work here.

**Comment by vantuyls** [comment]
Needs:
- [ ] Customize Report form including:
- [ ] date range
- [ ] filters drop downs (work type, status, visibility)
- [ ] sort column (date published)
- [ ] radio buttons for summary tables and month-by-month totals
- [ ] build reporting text (text immediately below report title - summary of filters and totals)
- [ ] table download button with options for csv download 
- [ ] for Month-by-month - monthly table by visibility
- [ ] for Summary table - tables by visibility, work type, resource type, status
