### ISSUE TITLE
Single Work Analytics Page

### ISSUE THREAD

**Issue by nestorw** [samvera/hyrax#2566]
### Descriptive summary
Analytics for a single work

<img width="1322" alt="c7-analytics-work" src="https://user-images.githubusercontent.com/1766876/35357540-dcbf7884-0121-11e8-95c2-09231d5cea21.png">

**Comment by vantuyls** [comment]
Needs:
- [ ]  metadata summary (see design mockup)
- [ ] button to View Work (takes one to the work showpage)
- [ ] total file size table
- [ ] activity summary with table
- [ ] monthly activity with table
- [ ] download buttons for the above tables

**Comment by vantuyls** [comment]
link at the top right of the screen "return to work reports" does not need to be surfaced until work reports are surfaced (likely the next milestone).

**Comment by jlhardes** [comment]
Testing on Nurax-dev with Analytics update and no analytics service connected shows the Works Report for a single work has all of these updates. There's no download option in a single work report but there is an export option for the Top Works table in the Works Report for all works. That includes both page views and downloads info (and actually seems to include all Works so there is no cut-off for Top Works). The metadata showing per work in the single work report seems to somewhat match the mock-up although I haven't seen any "Approved by", "Published on", or "Last modified on" info for any single work reports I viewed (Nurax-dev data can be light on activities like those but every single work report is showing deposited date and user info). The requests in this issue seem satisfied to me. @nestorw it has been a while, but do you have any concerns or questions?

**Comment by jlhardes** [comment]
Correction: Nurax-dev is connected to Google Analytics and that is why the single work analytics views and reports are available. When there is no analytics service connected there are no analytics graphs available from the Work view and the Analytics reports on the Dashboard (for Works and Collections) are also not available.

**Comment by jlhardes** [comment]
Closing issue as checklist is resolved.
