### ISSUE TITLE
Expected forwarding when batch adding works to a collection

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2690]
**This is an UBER issue that is being replaced by actionable issues addressing a single scenario each.  Issue numbers for these are beside each Scenario in the Expected Behavior section.  Descriptions in the actionable issues take precedence over any descriptions in this issue as they were updated to reflect the state of Hyrax at a more recent moment in time.**

----

### Descriptive summary

This issue lays out expected forwarding behavior when using one of the 3 methods for adding works to a collection.

### Rationale

Provide intuitive forwarding behavior that focuses on the actions a user will most like want to take next.

### Expected behavior

- [ ] Need to update specs added in PR #2687 to match the forwards described in this issue.

#### Scenario: Batch add works from Dashboard -> Works
- [x] SUCCESS:  -- no issue needed, expectations are met
  - [x] forwards to collection's admin show page where user can confirm that the works were added 
  - [x] shows flash message (green): Collection was successfully update.  
- [ ] FAILURE of all:  -- actionable Issue #4006
  - [ ] forwards to collection's admin show page
  - [ ] shows flash error (red): Collections Error: You have specified more than one of the same single-membership collection types: _name of collection type_ (_list of effected collection_)
- [ ] FAILURE of some:    -- actionable Issue #4007
  - [x] forwards to collection's admin show page
  - [ ] shows flash warn (yellow): Collection was partially update.  
  - [x] shows flash error (red): Collections Error: You have specified more than one of the same single-membership collection types: _name of collection type_ (_list of effected collection_)

#### Scenario: Batch add works from Dashboard -> Collections -> collection show page
NOTE: This is the same as for Batch add works from Dashboard -> Works
- [x] SUCCESS:    -- no issue needed, expectations are met
  - [x] forwards to collection's admin show page where user can confirm that the works were added 
  - [x] shows flash message (green): Collection was successfully update.  
- [ ] FAILURE of all:   -- actionable Issue #4008
  - [ ] forwards to collection's admin show page
  - [ ] shows flash error (red): Collections Error: You have specified more than one of the same single-membership collection types: _name of collection type_ (_list of effected collection_)
- [ ] FAILURE of some:   -- actionable Issue #4009
  - [x] forwards to collection's admin show page
  - [ ] shows flash warn (yellow): Collection was partially update.  
  - [x] shows flash error (red): Collections Error: You have specified more than one of the same single-membership collection types: _name of collection type_ (_list of effected collection_)

#### Scenario: Add a single work from Dashboard -> Works -> new/edit work form -> Relationships tab
- [x] SUCCESS:
  - [x] forwards to work's show page since primary task was updating the work which could include metadata, files, and multiple relationships
  - [x] shows flash message: Work "_work title_" successfully updated. 
- [ ] FAILURE:    -- actionable Issues #4010 (for new) and #4011 (for edit)
  - [x] stays on edit form (Description tab)
  - [x] no changes are saved
  - [x] shows flash error: Collections Error: You have specified more than one of the same single-membership collection types: _name of collection type_ (_list of effected collection_)
  - [ ] should NOT have second flash error section with no text

### Actual behavior

NOTE: At this writing, the failures that should happen do not.  So I am unable to state the actual behaviors for failure.  A PR is expected soon to fix this.

#### Scenario: Batch add works from Dashboard -> Works
* SUCCESS:  
  * forwards to collection's admin show page where user can confirm that the works were added 
  * shows flash message: Collection was successfully update.  
* FAILURE of all:
  * forwards to collection index page All Collections tab
  * shows flash warning: Collections Error: You have specified more than one of the same single-membership collection types: _name of collection type_ (_list of effected collection_)
* FAILURE of some:  
  * forwards to collection's show page
  * shows flash error: Collections Error: You have specified more than one of the same single-membership collection types: _name of collection type_ (_list of effected collection_)
  * shows flash message: Collection was successfully update.  

#### Scenario: Batch add works from Dashboard -> Collections -> collection show page
* SUCCESS:  
  * forwards to collection's admin show page where user can confirm that the works were added 
  * shows flash message: Collection was successfully update.  
* FAILURE of all:
  * forwards to collection index page All Collections tab
  * shows flash warning: Collections Error: You have specified more than one of the same single-membership collection types: _name of collection type_ (_list of effected collection_)
* FAILURE of some:  
  * forwards to collection's show page
  * shows flash error: Collections Error: You have specified more than one of the same single-membership collection types: _name of collection type_ (_list of effected collection_)
  * shows flash message: Collection was successfully update.  

#### Scenario: Add a single work from Dashboard -> Works -> new/edit work form -> Relationships tab
NOTE: SUCCESS/FAILURE is only known once the work is saved
* SUCCESS:
  * forwards to work's show page since primary task was updating the work which could include metadata, files, and multiple relationships
  * shows flash message: Work "_work title_" successfully updated. 
* FAILURE:  
  * stays on edit form (Description tab)
  * no changes are saved
  * shows flash error: Collections Error: You have specified more than one of the same single-membership collection types: _name of collection type_ (_list of effected collection_)
  * has second flash error section with no text

### Steps to reproduce the behavior

Prereq: 
* Create a single member collection type
  * Dashboard -> Settings -> Collection Types -> Create new collection type
  * Assign type name Single Membership and Save
  * On Settings tab, uncheck MULTIPLE MEMBERSHIP and Save changes
* Create two collection of single member type
  * Dashboard -> Collections -> New Collection -> select Single Membership type -> Create Collection
  * Assign Title SM1 for one collection and SM2 for the other and Save
* Create 6 works
  * Dashboard -> Works -> Add new work -> fill in requirements (titles: Work1, Work2, etc) -> Save

#### Scenario: Batch add works from Dashboard -> Works
1. Dashboard -> Works -> check box beside Work1 -> Add to Collection -> select SM1  -> Save changes

Verify SUCCESS expectations for this scenario

2. Dashboard -> Works -> check box beside Work1 -> Add to Collection -> select SM2  -> Save changes 

Verify FAILURE for all expectations for this scenario

3. Dashboard -> Works -> check box beside Work1 and Work2 -> Add to Collection -> select SM2  -> Save changes 

Verify FAILURE for some expectations for this scenario

#### Scenario: Batch add works from Dashboard -> Collections -> collection show page
1. Dashboard -> Collections -> click title for SM1 -> Add existing works to this collection
2. check box beside Work3 -> Add to Collection -> select SM1  -> Save changes

Verify SUCCESS expectations for this scenario

3. Dashboard -> Collections -> click title for SM2 -> Add existing works to this collection
4. check box beside Work3 -> Add to Collection -> select SM2  -> Save changes

Verify FAILURE for all expectations for this scenario

5. Dashboard -> Collections -> click title for SM2 -> Add existing works to this collection
6. check box beside Work3 and Work4 -> Add to Collection -> select SM2  -> Save changes 

Verify FAILURE for some expectations for this scenario

#### Scenario: Add a single work from Dashboard -> Works -> new/edit work form -> Relationships tab
1. Dashboard -> Works -> click title for Work5 -> Edit work -> Relationships tab
2. In Collections section, in field Select a collection..., type SM1 and Add and Save changes

Verify SUCCESS expectations for this scenario

3. Dashboard -> Works -> click title for Work5 -> Edit work -> Relationships tab
4. In Collections section, in field Select a collection..., type SM2 and Add and Save changes

Verify FAILURE expectations for this scenario

### Related work

PR #2687 - fix single membership and add single/multi-membership spec tests

**Comment by vantuyls** [comment]
@elrayle this looks merged. can we close the issue?

**Comment by no-reply** [comment]
@elrayle I'm also wondering about the status of this issue.

If there's work left here, could we break out smaller tickets and close this one?

**Comment by dlim87** [comment]
This is still occurring as of Hyrax 3.0 RC1

**Comment by no-reply** [comment]
there's a lot of behavior described in this ticket.

@samvera/hyrax-repo-managers i wonder if we couldn't get some help breaking this down into actionable chunks?

**Comment by dlim87** [comment]
To clarify, the failing behaviors are 

- **Batch add works from dashboard > works: Failure of all** - redirects to "all collections" instead of collection show page. The other two behaviors in this scenario work as expected
-  **Batch add works from dashboard > Collections > collection show page** - same as above ^

The other scenarios are behaving as expected

**Comment by elrayle** [comment]
Created separate actionable issues for each scenario.  I verified current behavior against expected behavior for each scenario as I created the issues.

* Issue #4006 Batch add works to collection from Dashboard->Works when all fail doesn't forward as expected
* Issue #4007 Batch add works to collection from Dashboard->Works when some fail doesn't forward as expected
* Issue #4008 Batch add works to collection from collection admin show page when all fail doesn't forward as expected
* Issue #4009 Batch add works to collection from collection admin show page when some fail doesn't forward as expected
* Issue #4010 Adding work to multiple single membership collections from new work form does not forward as expected
* Issue #4011 Adding work to multiple single membership collections from edit work form does not forward as expected

I am closing this issue in favor of the more atomic actionable issues.
