### ISSUE TITLE
Remove parent collections and subcollections from show page list doesn't work

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#2780]
### Descriptive summary
The "Remove" button in the Collections View/Show page for parent collection and subcollection lists, does not work.  The delete modal(s) are not triggered properly.  A previous commit changed the `id` attribute used to target the modal selection in a JavaScript click handler.

![remove-collections-button](https://user-images.githubusercontent.com/3020266/37115754-a848e37c-2211-11e8-8174-1153eeee11f8.png)

There's an additional anti-pattern occurring where a modal is created (with the same `id` attribute - illegal html and breaks selector functionality), for each parent collection or subcollection in each list.

### Expected behavior

Clicking either Remove button activates the modal which will then remove a collection.

### Actual behavior

Clicking either Remove button does not activate the necessary modal.

### Steps to reproduce the behavior

1. Log into Hyrax
2. Go to Dashboard > Collections
3. Make sure your collection has a parent or child collection so the list will display them.
3. Select your collection to view it, then try clicking Remove on the Parent or Subcollections item list.

### Related work
https://github.com/samvera/hyrax/issues/2618

### Tasks
- [ ] Update selector in the JavaScript for each Remove button click.
- [ ] Remove multiple instances of modals with the same `id` attribute.
- [ ] Update how the modal deletes.  Change from a form (as it currently is), to a link.
