### ISSUE TITLE
Accessibility - add aria attributes to dropdown menus

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#3043]
### Descriptive summary

From the Accessibility 360 Audit Report:

> Each button controls expandable content, but this is not indicated to screen reader users.

> Add an aria-controls attribute to each button that controls the expandable content and set the value of that attribute to equal the ID of the tag that wraps the expanded content. Also add an aria-expanded="true" attribute to each button when content is expanded, and false otherwise.

### Rationale

Accessibility improvement for screen readers.

### Tasks
Fix the following instances where this occurs:

- [ ] Dashboard > Authorize Proxies dropdown

![authorize-proxies](https://user-images.githubusercontent.com/3020266/39713264-ceec3a74-51eb-11e8-8bd0-7b5dc2467d88.png)

- [x] "All Collections" and "Your Collections" tabs > "Select" dropdowns in the table
- [x] Update Admin Sets action menu also

![actions-select-dropdown](https://user-images.githubusercontent.com/3020266/39713335-090c84c0-51ec-11e8-8db5-3ad967eb8e05.png)

- [x] "All Works" and "Your Works" tabs > "Select" dropdowns in the table

https://nurax.curationexperts.com/dashboard/my/works?locale=en (Similar to above screenshot)

- [x] Top nav dropdowns

![homepage-top-nav-dropdowns](https://user-images.githubusercontent.com/3020266/43917105-f8de500a-9bd4-11e8-94be-aec6444f8e3f.png)

**Comment by adamjarling** [comment]
The Authorize Proxies link above looks like is controlled by Select2... and is not a standard Bootstrap dropdown implementation.  Am going to bypass this for now.
