### ISSUE TITLE
Make wings persister pass valkyrie shared specs

### ISSUE THREAD

**Issue by hackartisan** [samvera/hyrax#3627]
Tests of a `Valkyrie::Resource` that used to be an `ActiveFedora::Base` object:
- [x] make `be_persisted` work #3628 
- [x] save
- [x] save_all, delete, wipe! #3647
- [x] add `created_at` and `updated_at` to Valkyrie resource attributes #3646 
- [x] https://github.com/samvera/hyrax/issues/3649 internal_resource needs to be a string
- [x] can override default id generation with a provided id (pending spec) #3661
- [ ] Once the "native" tests are ready / done, sort through this set of tests and delete anything that's really covered by those; keep only what's needed to enforce our specific behavior needs.

Tests of native `Valkyrie::Resource`s
- [x] be able to save valkyrie resources that were never AF resources #3629
- [ ] can save nested resources #3662
- [x] can persist single values #3663
- [x] stores created_at/updated_at #3664
- [x] can handle various RDF data types #3665
- [x] can handle various other data types #3666
- [x] can order members #3668
- [x] can remove members #3669
- [x] doesn't override a resource that already has an ID #3670
- [x] can find that resource again #3671
- [x] can delete objects #3672
- [x] optimistic locking #3673
- [ ] ordered properties #3674
- [ ] Remove all these inline tests and uncomment the `behaves_like` call.

**Comment by hackmastera** [comment]
It is sometimes helpful to look at the original valkyrie activefedora adapter, which was later removed: https://github.com/samvera/valkyrie/blob/0d3f92188ea28f83a2d2128ccc6116008b2dfc63/lib/valkyrie/persistence/active_fedora/persister.rb

**Comment by hackartisan** [comment]
I believe the 2 remaining features not implemented in wings, nested resources and ordered properties, are not currently supported hyrax features (i.e. active fedora does not support them). If that understanding is correct, I propose we close this as wontfix. It means wings will never be a fully implemented valkyrie adapter, but I believe it is intended as bridge code and slated for future deletion, so that's probably fine.

**Comment by hackartisan** [comment]
The items remaining in this issue that don't have their own issues are related to test cleanup. Since wings is bridge code it's likely not the best use of resources to tidy specs before deleting them; closing.
