### ISSUE TITLE
Replace calls to ActiveFedora::Base.where (removes 7 refs to ActiveFedora)

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3820]
### Prerequisites

This issue cannot be completed until the following issues are completed first...

* #3800  setup solr indexers and solr metadata adapter

----
### Descriptive summary

The `ActiveFedora::Base.where` is used to apply a solr query and return instances of Active Fedora objects.  

It is used to accomplish a few tasks in Hyrax...
* get a count of objects searching solr and counting results
* get a count of objects that the current user can see by searching solr, limiting results based on `current_ability`, and counting the filtered results
* get a set of objects

This issue involves removing references to `ActiveFedora::Base.where`.

### ActiveFedora code

Active Fedora class being replaced...

Example from app/models/hyrax/collection_type.rb
```
      ActiveFedora::Base.where(collection_type_gid_ssim: gid.to_s)
```

To locate, search code for `ActiveFedora::Base.where` in `app`.  You will also need to search for `.where`, but some of these will be for non `ActiveFedora::Base` objects (e.g. `Users`) and should not be updated as they are using `ActiveRecord #where`.  The ones for `ActiveFedora::Base` objects (e.g. `AdminSet`, `Collection`, `Work`, `FileSet`) will need to be updated.

### Replacement code

Pseudocode replacement code...
* query = build a solr query based on what was being passed to `ActiveFedora::Base.where` - Can existing [Hyrax::SolrQueryServiceBuilder](https://github.com/samvera/hyrax/blob/main/app/services/hyrax/solr_query_builder_service.rb) be used or expanded as a replacement for building the solr query?
* ids = submit query to [Hyrax::SolrService](https://github.com/samvera/hyrax/blob/main/app/services/hyrax/solr_service.rb) 
* resources = use [Wings::Valkyrie::QueryService #find_many_by_ids](https://github.com/samvera/hyrax/blob/main/lib/wings/valkyrie/query_service.rb#L72-L96) passing ids from solr search if resources are needed

Perhaps create a service that performs all these steps that can be used as a direct replacement for #where. 
 
### Considerations

* Can some uses of `where` to find related objects be replaced with calls to one of the [custom navigation queries](https://github.com/samvera/hyrax/tree/main/app/services/hyrax/custom_queries/navigators) or the standard [find_references_by](https://github.com/samvera/hyrax/blob/main/lib/wings/valkyrie/query_service.rb#L134-L150) query method?
* Do NOT replace this call if found in `lib/wings` directories.

### Impact on Testing

Not expected to require test changes.  All tests should pass with the replacement code.

**Comment by elrayle** [comment]
Checkout PR #3804 which as a first step replaces ActiveFedora::SolrService with Hyrax::SolrService which continues to call ActiveFedora::SolrService. 

Something similar might make a good first PR for this issue.

**Comment by lsitu** [comment]
@no-reply The `ActiveFedora::Base.where` call is used in `lib/wings` several times:
https://github.com/samvera/hyrax/blob/master/lib/wings/models/concerns/collection_behavior.rb#L25
https://github.com/samvera/hyrax/blob/master/lib/wings/valkyrie/query_service.rb#L137
https://github.com/samvera/hyrax/blob/master/lib/wings/valkyrie/query_service.rb#L150

It seems like we we shouldn't replace it (see the `Considerations` section in the description text). Is there anything can do for the ticket?

**Comment by elrayle** [comment]
### Remaining Work after PRs #4910 and #4929

#### searching for ActiveFedora::Base.where return 6 matches in 4 files

4 need the addition of method #accessible_by
* app/presenters/hyrax/admin_set_presenter.rb15
* app/presenters/hyrax/collection_presenter:85
* app/presenters/hyrax/collection_presenter:89
* app/presenters/hyrax/collection_presenter:93

2 others should follow the pattern established in #4929 
* app/models/concerns/hyrax/collection_behavior.rb:79
* app/models/hyrax/collection_type.rb:115

#### .where applied to ActiveFedora::Relation

3 uses of relation.where with relation being an ActiveFedora::Relation
* app/services/hyrax/statistics/query_service.rb:10
* app/services/hyrax/statistics/query_service.rb:48
* app/services/hyrax/statistics/over_time.rb:35

#### a few others that might also be using ActiveFedora where

3 that need further investigation
* app/services/hyrax/find_objects_via_solr_service.rb:19
* app/services/hyrax/statistics/works/count.rb:38
* app/services/hyrax/statistics/works/count.rb:39

**Comment by elrayle** [comment]
## Remaining Work after PRs #4910, #4929, and #4938

### searching for ActiveFedora::Base.where return 6 matches in 4 files

4 need the equivalent of `#accessible_by` added as a method in `Hyrax::SolrQueryService`

- [x] app/presenters/hyrax/admin_set_presenter.rb15 (Fixed in PR #5025)
- [x] app/presenters/hyrax/collection_presenter:85 (Fixed in PR #5025)
- [x] app/presenters/hyrax/collection_presenter:89 (Fixed in PR #5025)
- [x] app/presenters/hyrax/collection_presenter:93 (Fixed in PR #5025)

2 others should follow the pattern established in #4929 except using `Hyrax::SolrQueryService` as in PR #5024

- [ ] app/models/concerns/hyrax/collection_behavior.rb:79
- [ ] app/models/hyrax/collection_type.rb:115

### .where applied to ActiveFedora::Relation

3 uses of relation.where with relation being an ActiveFedora::Relation that should also follow the pattern established in #4929 except using `Hyrax::SolrQueryService` as in PR #5024

- [ ] app/services/hyrax/statistics/query_service.rb:10
- [ ] app/services/hyrax/statistics/query_service.rb:48
- [ ] app/services/hyrax/statistics/over_time.rb:35

### a few others that might also be using ActiveFedora where

3 that need further investigation

- [x] app/services/hyrax/find_objects_via_solr_service.rb:19 (Fixed in PR #5023)
- [ ] app/services/hyrax/statistics/works/count.rb:38
- [ ] app/services/hyrax/statistics/works/count.rb:39

## Examples

PR #5024 uses a single `SolrQueryService` method to build the query and uses the `#count` method to get the count in `DashboardHelperBehavior`.

```
Hyrax::SolrQueryService.new.with_field_pairs(field_pairs: field_pairs(user)).count
```

PR #5023 uses chained `SolrQueryService` methods to build the query and uses `#get_objects` to get `Valkyrie::Resource` objects in `MultipleMembershipChecker`

```
      Hyrax::SolrQueryService.new
                             .with_model(model: ::Collection)
                             .with_field_pairs(field_pairs: field_pairs, join_with: ' OR ')
                             .get_objects(use_valkyrie: true)
```
