### ISSUE TITLE
maximize flexibility of what can happen when an item in a workflow is edited

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#550]
### Descriptive summary

Workflows (and their configurations) should have flexibility to define editability for all roles related of an item and at all steps in the workflow.

### Rationale

Use cases for flexible workflow configs:
- User can deposit an item and always have access to edit the item. Item stays live in the system always. (this is like a fully self deposit repository with no mediation - think Scholarsphere?)
- User deposits item and immediately loses edit abilities unless the item comes back to them for editing (this is like a thesis document being submitted)
- Item in workflow is editable by all users of the system but users can still be notified of changes they need to make at different stages of the workflow (this is like a workflow for a digitization unit)
- A group of users need to be able to make edits at some step of the workflow (e.g. if any of the 10 people in the metadata department can make edits at a workflow "step")

### Expected behavior

Workflows in Hyrax will have a wide range of possible use cases and this requires that when one is defining a workflow, one has the flexibility to define, fairly specifically:
- [ ] Group/roles that can make edits to an item at each step of the worlkflow
- [ ] The visibility of an item at each step of the workflow (is it in an active or inactive state)
- [ ] All of these elements should be incorporated into the workflow.json to centralize configurability

### Related work

related issues (that initiated the discussion for this issue) include:
https://github.com/projecthydra/sufia/issues/3134
https://github.com/projecthydra-labs/hyrax/issues/172

@mjgiarlo @jeremyf @scholarworks @hannahfrost @escowles @tpendragon @jcoyne @randalldfloyd

**Comment by vantuyls** [comment]
I've tried to capture all the things we talked about this morning - let me know (or add/edit) if you see that i missed something.

**Comment by revgum** [comment]
I want to leave an open question that relates to workflow flexibility. We'd like to publish a new work to Hyrax, in an active state of the workflow tied to its admin set. When this work is updated in the future, will it be capable of being set to any state in the workflow that it is currently on? (Assuming that we are able to publish a new work to Hyrax bypassing the workflow and setting the state directly to 'active').

The use case here is for data migration from some other system (DSpace, possibly Oregon Digital) and having the ability to publish a new work, but still have the fully functional workflow after the work was published.

**Comment by mjgiarlo** [comment]
Works are capable of being set to any state that the current state can transition to, at any point assuming the current user has proper workflow responsibility. Right, @jcoyne @jeremyf?

**Comment by jeremyf** [comment]
For each state of a workflow there may exist actions that can transition the work to a new state. For each of those actions (and the current workflow state) the user must have permission (either at the Entity or Workflow level) to perform the action.

**Comment by jeremyf** [comment]
I believe an LDCX session should very much be a workflow conversation; What examples are we trying to model. Create the JSON to reflect those examples.

**Comment by mjgiarlo** [comment]
Thanks, @jeremyf.

**Comment by jcoyne** [comment]
@vantuyls I believe we already have these capabilities in the workflow engine. You just need to write a custom workflow template with these instructions encoded, right?

**Comment by vantuyls** [comment]
@revgum seems like we sorted out the workflow state issue locally, right? anything else on that?

@jcoyne i think one of the bullet points in the issue isn't addressed by workflow, namely: disallowing edit access to an item once the user has uploaded it.

**Comment by jcoyne** [comment]
@vantuyls that is addressed in workflow by the `RevokeEditFromDepositor` action.
https://github.com/samvera/hyrax/blob/master/lib/generators/hyrax/templates/mediated_deposit_workflow.json.erb#L51

**Comment by vantuyls** [comment]
hrm. didn't know that existed. I'll point @luisgreg99 at that spot.

**Comment by vantuyls** [comment]
possible that this is all resolved or had already been covered by work done on workflows. thoughts anyone? can we close this?

**Comment by mjgiarlo** [comment]
@vantuyls Agree that this can be closed. Thanks!
